fail_on_violations: true

ruby:
  enabled: false

coffeescript:
  enabled: false

javascript:
  enabled: false

eslint:
  enabled: true
  config_file: .javascript-style.json
  ignore_file: .javascript_ignore

scss:
  enabled: false

haml:
  enabled: false

go:
  enabled: false

swift:
  enabled: false
